/**
 */
package fr.polytech.mlg.releaze.house.polycreate.provider;

import fr.polytech.mlg.releaze.house.polycreate.util.PolycreateAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PolycreateItemProviderAdapterFactory extends PolycreateAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PolycreateItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.Program} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProgramItemProvider programItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.Program}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProgramAdapter() {
		if (programItemProvider == null) {
			programItemProvider = new ProgramItemProvider(this);
		}

		return programItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.Turn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnItemProvider turnItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.Turn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTurnAdapter() {
		if (turnItemProvider == null) {
			turnItemProvider = new TurnItemProvider(this);
		}

		return turnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.GoForward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoForwardItemProvider goForwardItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.GoForward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGoForwardAdapter() {
		if (goForwardItemProvider == null) {
			goForwardItemProvider = new GoForwardItemProvider(this);
		}

		return goForwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.OpenGrip} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpenGripItemProvider openGripItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.OpenGrip}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpenGripAdapter() {
		if (openGripItemProvider == null) {
			openGripItemProvider = new OpenGripItemProvider(this);
		}

		return openGripItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.CloseGrip} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CloseGripItemProvider closeGripItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.CloseGrip}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCloseGripAdapter() {
		if (closeGripItemProvider == null) {
			closeGripItemProvider = new CloseGripItemProvider(this);
		}

		return closeGripItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.BumpRight} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BumpRightItemProvider bumpRightItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.BumpRight}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBumpRightAdapter() {
		if (bumpRightItemProvider == null) {
			bumpRightItemProvider = new BumpRightItemProvider(this);
		}

		return bumpRightItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.BumpLeft} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BumpLeftItemProvider bumpLeftItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.BumpLeft}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBumpLeftAdapter() {
		if (bumpLeftItemProvider == null) {
			bumpLeftItemProvider = new BumpLeftItemProvider(this);
		}

		return bumpLeftItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.CliffRight} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CliffRightItemProvider cliffRightItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.CliffRight}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCliffRightAdapter() {
		if (cliffRightItemProvider == null) {
			cliffRightItemProvider = new CliffRightItemProvider(this);
		}

		return cliffRightItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.CliffLeft} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CliffLeftItemProvider cliffLeftItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.CliffLeft}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCliffLeftAdapter() {
		if (cliffLeftItemProvider == null) {
			cliffLeftItemProvider = new CliffLeftItemProvider(this);
		}

		return cliffLeftItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.AtStartingPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtStartingPointItemProvider atStartingPointItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.AtStartingPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtStartingPointAdapter() {
		if (atStartingPointItemProvider == null) {
			atStartingPointItemProvider = new AtStartingPointItemProvider(this);
		}

		return atStartingPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.CliffFront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CliffFrontItemProvider cliffFrontItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.CliffFront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCliffFrontAdapter() {
		if (cliffFrontItemProvider == null) {
			cliffFrontItemProvider = new CliffFrontItemProvider(this);
		}

		return cliffFrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.ObjectGrabbable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectGrabbableItemProvider objectGrabbableItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.ObjectGrabbable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectGrabbableAdapter() {
		if (objectGrabbableItemProvider == null) {
			objectGrabbableItemProvider = new ObjectGrabbableItemProvider(this);
		}

		return objectGrabbableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.NumeralValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumeralValueItemProvider numeralValueItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.NumeralValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumeralValueAdapter() {
		if (numeralValueItemProvider == null) {
			numeralValueItemProvider = new NumeralValueItemProvider(this);
		}

		return numeralValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.RandomValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RandomValueItemProvider randomValueItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.RandomValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRandomValueAdapter() {
		if (randomValueItemProvider == null) {
			randomValueItemProvider = new RandomValueItemProvider(this);
		}

		return randomValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.polytech.mlg.releaze.house.polycreate.GoTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoToItemProvider goToItemProvider;

	/**
	 * This creates an adapter for a {@link fr.polytech.mlg.releaze.house.polycreate.GoTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGoToAdapter() {
		if (goToItemProvider == null) {
			goToItemProvider = new GoToItemProvider(this);
		}

		return goToItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (programItemProvider != null)
			programItemProvider.dispose();
		if (stateItemProvider != null)
			stateItemProvider.dispose();
		if (turnItemProvider != null)
			turnItemProvider.dispose();
		if (goForwardItemProvider != null)
			goForwardItemProvider.dispose();
		if (functionItemProvider != null)
			functionItemProvider.dispose();
		if (openGripItemProvider != null)
			openGripItemProvider.dispose();
		if (closeGripItemProvider != null)
			closeGripItemProvider.dispose();
		if (bumpRightItemProvider != null)
			bumpRightItemProvider.dispose();
		if (bumpLeftItemProvider != null)
			bumpLeftItemProvider.dispose();
		if (cliffRightItemProvider != null)
			cliffRightItemProvider.dispose();
		if (cliffLeftItemProvider != null)
			cliffLeftItemProvider.dispose();
		if (atStartingPointItemProvider != null)
			atStartingPointItemProvider.dispose();
		if (cliffFrontItemProvider != null)
			cliffFrontItemProvider.dispose();
		if (objectGrabbableItemProvider != null)
			objectGrabbableItemProvider.dispose();
		if (numeralValueItemProvider != null)
			numeralValueItemProvider.dispose();
		if (randomValueItemProvider != null)
			randomValueItemProvider.dispose();
		if (goToItemProvider != null)
			goToItemProvider.dispose();
	}

}
